job/urls.py
from django.urls import path,include
from . import views 
from . import api

app_name = 'job'

urlpatterns = [
    path('',views.job_list, name='job_list'),
    path('post',views.post_job, name='post_job'),
    path('<str:slug>',views.job_detail,name='job_detail'),
    path('api/list',api.job_list_api,name='job_list_api'),
    path('api/detail/<int:id>',api.job_detail_api,name='job_detail_api'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/',include('job.urls',namespace='jobs')),
    path('contact-us/',include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from distutils import extension
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.

def uploaded_images(instance,filename):
    imagename , extension = filename.split(".")
    return "job/%s.%s"%(instance.id,extension)

class Job(models.Model):
    JOB_TYPE =(
        ('Full Time','Full Time'),
        ('Part Time','Part Time')
    )
    owner = models.ForeignKey(User,related_name='owner',on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    # location
    job_type = models.CharField(max_length=15,choices=JOB_TYPE)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category',on_delete=models.CASCADE)
    image = models.ImageField(upload_to =uploaded_images)
    slug = models.SlugField(blank=True,null=True)


    def save(self,*args,**kwrgs):
        self.slug = slugify(self.title)
        super(Job,self).save(*args,**kwrgs)

    def __str__(self):
        return self.title

class Category (models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

class Job_Aplication(models.Model):
    job = models.ForeignKey(Job,related_name='apply_job',on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.URLField(blank=True, null=True)
    cv = models.FileField(upload_to='applications/')
    cover_letter = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

job/views.py
from django.shortcuts import render ,redirect
from django.urls import reverse
from .models import Job
from django.core.paginator import Paginator
from .form import JobApplicationForm , JobPostForm
from django.contrib.auth.decorators import login_required
from.filters import JobFilter

# Create your views here.

def job_list(request):
    job_list = Job.objects.all()
    job_filter =JobFilter(request.GET,queryset=job_list)
    job_list = job_filter.qs
    paginator =Paginator(job_list,3) # this will show three item in the page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context ={'jobs':page_obj,'job_filter':job_filter}
    return render(request,'job/job_list.html',context)

def job_detail(request,slug):
    job_detail = Job.objects.get(slug=slug)

    if request.method =='POST':
        form = JobApplicationForm(request.POST , request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.job = job_detail
            myform.save()

            return redirect(reverse('jobs:job_list'))

    else:
        form = JobApplicationForm()

    context = {'details':job_detail,'form':form}
    return render(request,'job/job_detail.html',context)

@login_required(login_url='login')
def post_job(request):
    if request.method =='POST':
        form = JobPostForm(request.POST , request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()

            return redirect(reverse('jobs:job_list'))

    else:
        form = JobPostForm()

    context = {'form':form}
    return render(request,'job/post_job.html',context)

job/templates/Job/job_detail.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap4 %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{details.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{details.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{details.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{details.description}}</p>
                        </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form method = "post" enctype="multipart/form-data">
                            {%csrf_token%}
                            {% bootstrap_form form %}
                            
                            <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                            
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{details.published_at|date:'d M o'}}</span></li>
                                <li>Vacancy: <span>{{details.vacancy}}</span></li>
                                <li>Salary: <span>{{details.salary}} k/y</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span> {{details.job_type }}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }
                              
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock  %}

job/templates/Job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs.count}}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form >
                                {% bootstrap_form job_filter.form %}
                                
                                <div class="reset_btn">
                                    <button  class="boxed-btn3 w-100 mt-3 mb-3" type="submit">Search</button>
                                </div>
                            </form>
                        </div>
        
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in jobs %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <!-- <div class="thumb">
                                            <img src="" alt="">
                                        </div> -->
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line:{{job.published_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% if jobs.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                            {% if jobs.has_previous %}
                                            <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                            {% endif %}
                                            {% for x in jobs.paginator.page_range %}
                                            <li><a href="?page={{x}}"><span>{{x}}</span></a></li>
                                            {% endfor %}
                                            {% if jobs.has_next %}
                                            <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

{% endblock %}  

job/templates/Job/post_job.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap4 %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Post Your Job..</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">  
                    <div class="apply_job_form white-bg">
                        <h4>Post Job</h4>
                        <form method = "post" enctype="multipart/form-data">
                            {%csrf_token%}
                            {% bootstrap_form form %}
                            <button class="boxed-btn3 w-100" type="submit">Add Job</button>
                            
                        </form>
                    </div>
                </div>

        
            </div>
        </div>
    </div>

{% endblock  %}