accounts/urls.py
from django.urls import path,include
from . import views

app_name = 'job'

urlpatterns = [
    path('signup',views.signup, name='signup'),
    path('profile/',views.profile, name='profile'), 
    path('profile/edit',views.edit_profile, name='edit_profile'),  
]

job/urls.py
from django.urls import path,include
from . import views 
from . import api

app_name = 'job'

urlpatterns = [
    path('',views.job_list, name='job_list'),
    path('post',views.post_job, name='post_job'),
    path('<str:slug>',views.job_detail,name='job_detail'),
    path('api/list',api.job_list_api,name='job_list_api'),
    path('api/detail/<int:id>',api.job_detail_api,name='job_detail_api'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/',include('job.urls',namespace='jobs')),
    path('contact-us/',include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    city = models.ForeignKey('City',related_name='user_city',on_delete=models.CASCADE,null=True,blank=True)
    phone_number = models.CharField(max_length=15)
    image = models.ImageField(upload_to ='profile/')

    def __str__(self):
        return self.user.username


# create new user ----> create new profile using django signals

@receiver(post_save,sender = User)
def create_user_profile(sender,instance,created,**kwrgs):
    if created:
        Profile.objects.create(user = instance)



class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields= ['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model =  User
        fields = ['username','first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model =  Profile
        fields = ['city','phone_number','image']

accounts/views.py
from django.urls import reverse
from multiprocessing import context
import re
from django.shortcuts import render , redirect
from .forms import SignupForm , UserForm , ProfileForm
from django.contrib.auth import authenticate , login
from .models import Profile

# Create your views here. 
def signup(request):
    if request.method =='POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile/')
    else:
        form =SignupForm()

    context ={'form':form}
    return render(request,'registration/signup_form.html',context)



def profile(request):
    profile = Profile.objects.get(user = request.user)
    context ={'profile':profile}
    return render(request,'accounts/profile.html',context)

def edit_profile(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        usform = UserForm(request.POST,instance=request.user)
        prform = ProfileForm(request.POST,request.FILES,instance=profile)
        if usform.is_valid() and prform.is_valid():
            usform.save()
            prform.save(commit=False)
            prform.user = request.POST
            prform.save()
            return redirect(reverse('accounts:profile'))
    else:
        usform = UserForm(instance=request.user)
        prform = ProfileForm(instance=profile)

    context={'usform':usform,'prform':prform}
    return render(request,'accounts/profile_edit.html',context)

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap4 %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{details.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
            
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile.user}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                            </ul>
                        </div>
                        <div class="p-5">
                            <a href="{% url 'accounts:edit_profile' %}" class="boxed-btn3 w-100">Edit Profile</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock  %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap4 %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">  
                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form method = "post" enctype="multipart/form-data">
                            {%csrf_token%}
                            {% bootstrap_form usform %}
                            {% bootstrap_form prform %}

                            <button class="boxed-btn3 w-100 mt-3 mb-3" type="submit">submit</button>
                            
                        </form>
                    </div>
                </div>

        
            </div>
        </div>
    </div>

{% endblock  %}